[package]
name = "bencher_macro"
authors = ["Xiangpeng Hao <haoxiangpeng123@gmail.com>"]
version = "0.0.0"
edition = "2018"
publish = false

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = "1.0"
